openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://www.sample.com/api/v1
    description: App server
  - url: https://localhost:3000/api/v1
    description: Local server
paths:
  /status:
    get:
      security:
        - BearerAuth: []

      operationId: general
      responses:
        '200':
          description: OK
  /sample:
    get:
      operationId: general
      responses:
        '200':
          description: OK

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
